# Generated by Django 2.1.2 on 2021-11-02 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdetails',
            old_name='passwd',
            new_name='address',
        ),
        migrations.AddField(
            model_name='userdetails',
            name='dob',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
