# Generated by Django 3.0.8 on 2021-11-07 11:00

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_auto_20211105_1613'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user2',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='profile',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='user'),
        ),
        migrations.DeleteModel(
            name='FriendRequest',
        ),
    ]
